### PR TITLE
Rayan Alsaleh Homework submission

### PR DESCRIPTION
**Pull request by Rayan-Alsaleh**

### CODE REVIEW

**Comment by Rayan-Alsaleh** [comment]
My own site

**Comment by morojAlh** [comment]
Is it the last version?

**Comment by Rayan-Alsaleh** [comment]
the last version of what?

**Comment by morojAlh** [comment]
I mean did you modify your website to meet the requirements?

**Comment by Rayan-Alsaleh** [comment]
I tried to put most of the appropriate requirements for my site idea

**Comment by morojAlh** [comment]
| Technical Requirements                                                                                                                                                        | Does Not Meet Expectations (0) | Meets Expectations (1) | Exceeds Expectations (2) |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|------------------------|--------------------------|
| Link both pages together using `a` tag                                                                                                                                        |                                |            ✓           |                          |
| Use a unique `title` and a single unique `h1` tag                                                                                                                             |                                |            ✓           |                          |
| Show images using `img` tags including unique `alt` attributes                                                                                                                |                                |            ✓           |                          |
| Use an external CSS stylesheet to style your pages                                                                                                                            |                                |                        |           ✓              |
| Select at least 5 elements on the page and apply at least 5 different css properties (`font-size`, `color`, `font-family`, `background`, `text-decoration`) to these elements |                                |                        |           ✓              |
| Use at least 6 different HTML tags (`h1`, `h2`, `h3`, `h4`, `h5`, `h6`, `p`, `ul`, `ol`, `a`, `img`) on your pages                                                            |                                |                        |           ✓              |
| Follow naming conventions, maintain consistency across your .html and .css files                                                                                              |                                |             ✓          |                          |
| Indent nested elements to increase your code's readability                                                                                                                    |                                |             ✓          |                          |
| TOTAL: 11/16                                                                                                                                                              |                                |                        |                          |

**Comment by Rayan-Alsaleh** [comment]
Is this good ? :)

**Comment by morojAlh** [comment]
More than good 👍🏼

**Comment by Rayan-Alsaleh** [comment]
Thank you for your response and to clarify some information :) .

**Pull request closed without merging**
